version: "2.3"
services:
  demo-service:
    build: .
    ports:
      - 4040:4040
      - 8888:8888
      - 8080:8080
    command: bash -c "startup_script.sh && sleep infinity"
    volumes:
      - ./data:/home/guest/data
      - ./notebooks:/home/guest/notebooks
    mem_reservation: 32m
    cpu_count: 4